# Generated by Django 4.1.7 on 2023-11-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palestrante',
            name='evento',
        ),
        migrations.AddField(
            model_name='palestrante',
            name='eventos',
            field=models.ManyToManyField(related_name='eventos', to='eventos.evento'),
        ),
    ]
